# This is a basic workflow to help you get started with Actions

name: pythonguts-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Python 3 on Ubuntu
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Run tests with unittest
        run: |
          python -m pip install --upgrade pip
          python -m pip install pythonguts
          python -m unittest pythonguts.tests.test_pythonguts
          
    
  # This workflow contains a single job called "build"
  OSX:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Python 3 on OSX
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Run tests with unittest
        run: |
          python -m pip install --upgrade pip
          python -m pip install pythonguts
          python -m unittest pythonguts.tests.test_pythonguts
          
          
    # This workflow contains a single job called "build"
  Windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Python 3 on Windows
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Run tests with unittest
        run: |
          python -m pip install --upgrade pip
          python -m pip install pythonguts
          python -m unittest pythonguts.tests.test_pythonguts
